runtime: nodejs
env: flex

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(js|css|png|jpg|ico))$
    static_files: build/\1
    upload: build/.*\.(js|css|png|jpg|ico)$

  - url: /.*
    script: auto
    secure: always
